DOAN_14/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DOAN_14.Models;

namespace DemoDB2.Controllers
{
    public class CategoriesController : Controller
    {
        DBFourteenEntities database = new DBFourteenEntities();
        // GET: Categories
        public ActionResult Index(string _name)
        {
            if (_name == null)
                return View(database.Categories.ToList());
            else
                return View(database.Categories.Where(s => s.NameCate.Contains(_name)).ToList());

        }
        [HttpGet]
        public ActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Create(Category cate)
        {
            try
            {
                database.Categories.Add(cate);
                database.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return Content("Trùng khóa");
            }
            //return View();
        }
        public ActionResult Details(int id)
        {

            return View(database.Categories.Where(s => s.Id == id).FirstOrDefault());
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View(database.Categories.Where(s => s.Id == id).FirstOrDefault());
        }
        [HttpPost]
        public ActionResult Edit(int id, Category cate)
        {
            database.Entry(cate).State = System.Data.Entity.EntityState.Modified;
            database.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            return View(database.Categories.Where(s => s.Id == id).FirstOrDefault());
        }
        [HttpPost]
        public ActionResult Delete(int id, Category cate)
        {
            try
            {
                cate = database.Categories.Where(s => s.Id == id).FirstOrDefault();
                database.Categories.Remove(cate);
                database.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return Content("This data is using orther table, Error Delete! ");
            }

        }
        // Action PartialViewResult
    
        public PartialViewResult CategoryPartial()
        {
            var cateList = database.Categories.ToList();
            return PartialView(cateList);
        }

    }
}

DOAN_14/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DOAN_14.Models;
using PagedList;

namespace DOAN_14.Controllers
{
    public class ProductsController : Controller
    {
        private DBFourteenEntities db = new DBFourteenEntities();

        // GET: Products
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Category1);
            return View(products.ToList());

        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }
        public ActionResult DetailsCustomer(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.Category = new SelectList(db.Categories, "IDCate", "NameCate");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,NamePro,DecriptionPro,Category,Price,ImagePro")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Category = new SelectList(db.Categories, "IDCate", "NameCate", product.Category);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.Category = new SelectList(db.Categories, "IDCate", "NameCate", product.Category);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,NamePro,DecriptionPro,Category,Price,ImagePro")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Category = new SelectList(db.Categories, "IDCate", "NameCate", product.Category);
            return View(product);
        }
        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult ProductList(string category, int? page, string SearchString, double min = double.MinValue, double max = double.MaxValue)
        {
            // Tạo Products và có tham chiếu đến Category
            var products = db.Products.Include(p => p.Category1);
            // Tìm kiếm chuỗi truy vấn theo category
            if (category == null)
            {
                products = db.Products.OrderByDescending(x => x.NamePro);
            }
            else
            {
                products = db.Products.OrderByDescending(x => x.Category).Where(x => x.Category == category);
            }
            //Tìm kiếm chuỗi truy vấn theo NamePro, nếu chuỗi truy vấn SearchString khác rỗng, null
            if (!String.IsNullOrEmpty(SearchString))
            {
                products = products.Where(s => s.NamePro.Contains(SearchString));
            }
            // Tìm kiếm chuỗi truy vấn theo đơn giá
            if (min >= 0 && max > 0)
            {
                products = db.Products.OrderByDescending(x => x.Price).Where(p => (double)p.Price >= min && (double)p.Price <= max);
            }
            //return View(products.ToList());
            // Khai báo mỗi trang 4 sản phẩm
            int pageSize = 8;
            // Toán tử ?? trong C# mô tả nếu page khác null thì lấy giá trị page, còn
            // nếu page = null thì lấy giá trị 1 cho biến pageNumber.
            int pageNumber = (page ?? 1);
            // Nếu page = null thì đặt lại page là 1.
            if (page == null) page = 1;
            // Trả về các product được phân trang theo kích thước và số trang.
            return View(products.ToPagedList(pageNumber, pageSize));

        }
        public ActionResult AllProductList(string category, int? page, string SearchString, double min = double.MinValue, double max = double.MaxValue)
        {
            // Tạo Products và có tham chiếu đến Category
            var products = db.Products.Include(p => p.Category1);
            // Tìm kiếm chuỗi truy vấn theo NamePro (SearchString)
            if (!String.IsNullOrEmpty(SearchString))
            {
                products = db.Products.OrderByDescending(x => x.Category).Where(s =>s.NamePro.Contains(SearchString.Trim()));
            }
            // Tìm kiếm chuỗi truy vấn theo đơn giá
            if (min >= 0 && max > 0)
            {
                products = db.Products.OrderByDescending(x => x.Price).Where(p => (double)p.Price >= min && (double)p.Price <= max);
            }
            return View(products.ToList());

        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DOAN_14/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/css/ADMINLAYOUT.css" type="text/css" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/92e7113135.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="navbar-fixed-top" >
        <header class="header">
            <table class="header-table" style=" text-align: center">
                <tr class="header1">
                    <td style="width:85%"></td>
                    <td colspan="2"></td>
                    <td>
                        <ul>
                            <li style="">
                                @if (Session["NameUser"] == null)
                                {
                                <span style="color: #E5D9B6 ">Xin chào&emsp;&emsp;&emsp;&emsp;</span>
                                }
                                else
                                {
                                    <span style="color: #E14D2A;"><text style="color:black;">Xin chào Admin</text> @Session["NameUser"]</span>
                                }
                            </li>
                        </ul>
                    </td>
                </tr>
            </table>
            <table class="header-table" style="text-align:center;">
                <tr class="header2">
                    <td style="width:30%"><a class="shop-name" href="~/Products/ProductList">FOURTEEN</a></td>
                    <td><a class="header2-product" href="~/LoginUser/Index/?chon=1">SẢN PHẨM</a></td>
                    <td><a class="header2-product" href="~/LoginUser/Index/?chon=2">LOẠI SẢN PHẨM</a></td>
                    <td><a class="header2-product" href="~/LoginUser/Index/?chon=3">KHÁCH HÀNG</a></td>
                    <td><a class="header2-product" href="~/LoginUser/Index/?chon=4">ĐƠN HÀNG</a></td>
                    <td><a class="header2-product" href="~/LoginUser/Index/?chon=5">PHÂN QUYỀN</a></td>
                    <td style="width:20%"></td>
                </tr>
            </table>
        </header>
    </div>
    @RenderBody()
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <footer style=" height: 40px; text-align: center; padding: 10px; color:black; clear:both" ;>
        <b style="color: black;">
            &copy; @DateTime.Now.Year - Admin Group 14
        </b>
    </footer>
</body>
</html>

DOAN_14/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/css/LAYOUT.css" type="text/css" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/92e7113135.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="navbar-fixed-top">
        <header class="header">
            <table class="header-table" style="background-color: white; text-align: center;">
                <tr class="header1">
                    <td style="width:57%"></td>
                    <td colspan="2"></td>
                    <td><a class="lienket" href="#">Tiếng Việt ▾</a></td>
                    <td><a class="lienket" href="~/Customers/CreateCustomer">Đăng Ký</a></td>
                    <td><a class="lienket" href="~/Customers/LoginCus">Đăng Nhập</a></td>
                    <td><a class="lienket" href="@Url.Action("LogOutUser","LoginUser")">Đăng Xuất</a></td>
                    <td>
                        <ul>
                            <li style="text-align:center">
                                @if (Session["NameCus"] == null)
                                {
                                <span style="color:white">Xin chào&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;</span>
                                }
                                else
                                {
                                    <span style="color: #E14D2A; background-color: #E5D9B6; padding: 2px 5px; border-radius: 20px; "><text style="color:black;">Xin chào</text>
                                @Session["NameCus"]</span>
                                }
                            </li>
                        </ul>
                    </td>
                </tr>
            </table>
            <table class="header-table" style="text-align:center">
                <tr class="header2">
                    <td style="width:30%"><a class="shop-name" href="~/Products/ProductList">FOURTEEN</a></td>
                    <td class="header2-info">
                        <ul>
                            <li>
                                <a class="header2-product-title" style="text-align: center;" href="#">&emsp;&ensp;SẢN PHẨM ▾</a>
                                <ul class="dropdown">
                                    @{ Html.RenderAction("CategoryPartial", "Categories");}
                                </ul>
                            </li>
                        </ul>
                    </td>
                    <td><a class="lienket" href="~/Home/Contact">LIÊN HỆ</a></td>
                    <td><a class="lienket" style="text-align: center" href="~/Home/Index">GIỚI THIỆU</a></td>
                    <td class="header2-info">
                        <ul>
                            <li>
                                <a class="header2-product-title" style="text-align: center;" href="#">&emsp;&emsp;QUẢN LÝ ▾&emsp;&emsp;</a>
                                <ul class="dropdown">
                                    <li><a class="header2-product" href="~/LoginUser/Index/?chon=1">SẢN PHẨM</a></li>
                                    <li><a class="header2-product" href="~/LoginUser/Index/?chon=2">LOẠI SẢN PHẨM</a></li>
                                    <li><a class="header2-product" href="~/LoginUser/Index/?chon=3">KHÁCH HÀNG</a></li>
                                    <li><a class="header2-product" href="~/LoginUser/Index/?chon=4">ĐƠN HÀNG</a></li>
                                    <li><a class="header2-product" href="~/LoginUser/Index/?chon=5">PHÂN QUYỀN</a></li>
                                </ul>
                            </li>
                        </ul>
                    </td>
                    <td colspan="2" class="header-search">
                        @using (Html.BeginForm("ProductList", "Products", FormMethod.Get))
                        {
                            <i class="fa-solid fa-magnifying-glass" style="background-color: white;"></i>
                            <input class="search" name="SearchString" type="search" placeholder="Tìm kiếm">
                        }
                    </td>
                    <td>
                        <a class="lienket" style="text-align:center; background-color:white" href="~/ShoppingCart/ShowCart"><i class="fa-solid fa-cart-shopping"></i></a>
                        @Html.Action("BagCart", "ShoppingCart")
                    </td>
                </tr>
            </table>
        </header>
    </div>
    </div>
    @RenderBody()
    <br>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <footer class="main-footer mainfooter-toolbar " style="background-color: #808080;color:white">
        <div class="main-footer--bottom">
            <div class="container">
                <div class="row">

                    <div class="col-xs-12 col-sm-6 col-md-3 col-lg">
                        <div class="footer-col footer-block">
                            <h4 class="footer-title">	Giới thiệu</h4>
                            <div class="footer-content">
                                <p>
                                    FOURTEEN ESSENCE
                                </p>
                                <div class="logo-footer">
                                    <a href="">
                                        <img src="https://imjustcreative.com/wp-content/uploads/2014/04/Fourteen-Logo-Design-by-WeAreMash.jpg" style="width:150px;">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-3 col-lg">
                        <div class="footer-col footer-block">
                            <h4 class="footer-title">
                                Thông tin liên hệ
                            </h4>
                            <div class="footer-content toggle-footer" style="width: 500px; text-align:left;">
                                <li>
                                    <span>Địa chỉ:</span>                   <br />
                                    <strong>
                                        CN1: 828 Sư Vạn Hạnh, P.12, Q.10        <br />
                                        CN2: M4-M7-M9 Thất Sơn, P.15, Q.10      <br />
                                        CN3: 298-304 Cao Thắng, P.12, Q.10      <br />
                                        CN4: 357 Lê Hồng Phong, P.2, Q.10       <br />
                                        CN5: 32 Trường Sơn, P.2, Q.Tân Bình     <br />
                                        CN6: Quốc lộ 22, x.Tân Xuân, h.Hóc Môn  <br />
                                    </strong>
                                </li>
                                <li>
                                    <span>Điện thoại:</span> <strong> 0126497251</strong>
                                </li>
                                <li>
                                    <span>Mail:</span> <strong> fourteenclo@gmail.com</strong>
                                </li>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-3 col-lg">
                        <div class="footer-col footer-block">
                            <h4 style="margin-left:120px">
                                FANPAGE
                            </h4>
                            <div class="footer-content">
                                <!-- Facebook widget -->
                                <div class="footer-static-content">
                                    <div class="fb-page" data-href="https://www.facebook.com/huflit.edu.vn" data-height="300" data-small-header="false" data-adapt-container-width="true" 
                                         data-hide-cover="false" data-show-facepile="true" data-show-posts="false" style="margin-left:120px;">	</div>
                                </div>
                                <div style="clear:both;"></div>
                                <!-- #Facebook widget -->
                                <script>
                                    setTimeout(function () {
                                        (function (d, s, id) {
                                            var js, fjs = d.getElementsByTagName(s)[0];
                                            if (d.getElementById(id)) return;
                                            js = d.createElement(s); js.id = id;
                                            js.src = "//connect.facebook.net/en_US/sdk/xfbml.customerchat.js#xfbml=1&version=v2.0";
                                            fjs.parentNode.insertBefore(js, fjs);
                                        }(document, 'script', 'facebook-jssdk'));
                                    }, 5000);
                                </script>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="main-footer--copyright">
            <div class="container">
                <div class="main-footer--border" style="text-align:center">
                    <p>Copyright © 2022 <a href="https://huflit.edu.vn/"> FOURTEEN</a>. <a target='_blank' href='https://huflit.edu.vn/'>Powered by 14</a></p>
                </div>
            </div>
        </div>
    </footer>

</body>
</html>